name: Deploy to GitHub Pages

on:
  push:
    branches: [main, feature/new-styles]

permissions:
  contents: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install

      - name: Build site (Main)
        if: github.ref == 'refs/heads/main'
        run: pnpm run build
        env:
          BASE_URL: '/ps'

      - name: Build site (New Styles Preview)
        if: github.ref == 'refs/heads/feature/new-styles'
        run: pnpm run build
        env:
          BASE_URL: '/ps/new-styles'

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
          # 'main' va a la raíz, 'feature/new-styles' va a la carpeta 'new-styles'
          destination_dir: ${{ github.ref == 'refs/heads/main' && '.' || 'new-styles' }}
          keep_files: true
